# Generated by Django 4.0 on 2022-03-21 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0014_article_like_count_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
