# Generated by Django 4.0 on 2022-03-25 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0015_comment_comment_like_count_comment_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_like_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
